FROM rust AS builder
WORKDIR /app
COPY Cargo.toml .
RUN mkdir src && echo "fn main(){}" > src/main.rs
RUN cargo build --release
COPY . .
COPY src/main.rs src/main.rs
RUN touch src/main.rs
RUN cargo build --release
RUN mv $(find target/release/ -maxdepth 1 -type f -executable) /app/bin

FROM debian
COPY --from=builder /app/bin /usr/bin/app
CMD app