[package]
name = "common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusttype = { version = "*", optional = true }

[features]
default = ["f64", "type"]
f64 = []
f32 = []
type = ["rusttype"]
